
providers:
  google:
    type: oauth2
    client_id_env: GOOGLE_CLIENT_ID
    client_secret_env: GOOGLE_CLIENT_SECRET
    auth_url: https://accounts.google.com/o/oauth2/v2/auth
    token_url: https://oauth2.googleapis.com/token
    userinfo_url: https://openidconnect.googleapis.com/v1/userinfo
    scopes: [openid, email, profile]

  apple:
    type: oauth2
    auth_url: https://appleid.apple.com/auth/authorize
    token_url: https://appleid.apple.com/auth/token
    scopes: [name, email]

  github:
    type: oauth2
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    userinfo_url: https://api.github.com/user
    scopes: [user:email]
